# Generated by Django 5.2.1 on 2025-05-11 12:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='groups',
            table='Groups',
        ),
    ]
