# Generated by Django 5.2.1 on 2025-05-11 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_alter_groups_table'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='dayoftheweek',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='dishes',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='groups',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='menu',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='selection',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='students',
            options={'managed': False},
        ),
    ]
